/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import java.util.Arrays;
import java.util.List;
import java.util.Vector;
import javax.swing.JTextField;

/**
 *
 * @author hanh
 */
public class dieuChe extends javax.swing.JFrame {

    private Vector<JTextField> listOfC;
    private final int dx = 25 * 3;
    private final int dy = 25;
    private final int space = 10;
    private int X_BOARD;
    private int Y_BOARD;
    private int X_INIT;
    private int Y_INIT;
    
    public dieuChe() {
        initComponents();
        setTitle("Điều chế");
        initVars();
    }

    private void initVars(){
        X_BOARD = contain.getWidth();
        Y_BOARD = contain.getHeight();
        
        listOfC = new Vector<JTextField>();                
        
        X_INIT = (int)plus.getLocation().getX();
        Y_INIT = (int)plus.getLocation().getY();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contain = new javax.swing.JPanel();
        plus = new javax.swing.JButton();
        ok2 = new javax.swing.JButton();
        chatdc = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        output = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        contain.setBackground(new java.awt.Color(204, 204, 255));

        plus.setText("+");
        plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout containLayout = new javax.swing.GroupLayout(contain);
        contain.setLayout(containLayout);
        containLayout.setHorizontalGroup(
            containLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(plus, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(294, Short.MAX_VALUE))
        );
        containLayout.setVerticalGroup(
            containLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(plus)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        getContentPane().add(contain, new org.netbeans.lib.awtextra.AbsoluteConstraints(404, 120, 350, 130));

        ok2.setText("Ok");
        ok2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ok2MouseClicked(evt);
            }
        });
        getContentPane().add(ok2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 265, 44, -1));

        chatdc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chatdcActionPerformed(evt);
            }
        });
        getContentPane().add(chatdc, new org.netbeans.lib.awtextra.AbsoluteConstraints(515, 266, 87, -1));

        jLabel1.setText("Chất điều chế:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 265, 106, 23));

        output.setEditable(false);
        output.setBackground(new java.awt.Color(255, 204, 204));
        output.setColumns(20);
        output.setRows(5);
        jScrollPane1.setViewportView(output);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(404, 300, 350, 128));

        jLabel2.setText("Nhập các chất ban đầu");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, 296, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\OS\\Desktop\\ChemistryApp\\hoahoc\\Dieuche.jpg")); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 380, 390));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/dieuche2.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 90));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void plusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusActionPerformed
        int x_plus = (int)plus.getLocation().getX();
        int y_plus = (int)plus.getLocation().getY();

        JTextField tx = new JTextField();
        tx.setSize(dx, dy);
        tx.setLocation(x_plus, y_plus);
        contain.add(tx);
        tx.setVisible(true);

        listOfC.add(tx);

        if (x_plus + 2 * dx + space > X_BOARD ){
            plus.setLocation(X_INIT, y_plus + dy);
        }
        else{
            plus.setLocation(x_plus + dx + space, y_plus);
        }
    }//GEN-LAST:event_plusActionPerformed

    private void ok2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ok2MouseClicked
        List <String> list = new Vector<String>();
        for (JTextField textField : listOfC){
            if (textField.getText().length() > 0) 
                list.add(textField.getText());
        }
        
        process.dieuChe dc = new process.dieuChe(list);
        int id = dc.find(chatdc.getText());
        
        String X = "";
        for (String pthh : dc.showPath(id)){
            X += pthh + "\n";
        }
        output.setText(X);
    }//GEN-LAST:event_ok2MouseClicked

    private void chatdcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chatdcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chatdcActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dieuChe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dieuChe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dieuChe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dieuChe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dieuChe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField chatdc;
    private javax.swing.JPanel contain;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton ok2;
    private javax.swing.JTextArea output;
    private javax.swing.JButton plus;
    // End of variables declaration//GEN-END:variables
}
